"""news

Revision ID: 454e59c604bf
Revises: db730b053d58
Create Date: 2024-11-12 16:22:18.752052

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '454e59c604bf'
down_revision: Union[str, None] = 'db730b053d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_news_id_key', 'news', type_='unique')
    op.drop_column('news', 'news_id')
    op.add_column('userdata', sa.Column('mute', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'mute')
    op.add_column('news', sa.Column('news_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('news_news_id_key', 'news', ['news_id'])
    # ### end Alembic commands ###
